# CodeRabbit CI (safe, non-invasive) configuration for base-app
# This configuration is intentionally conservative: it performs checks
# without changing code or committing build artifacts.
#
# Notes:
# - The runner/syntax below is generic. Replace the `checkout` step with
#   your CodeRabbit runner's default repository checkout command if necessary.
# - This CI does not run `gofmt -w`; it only checks formatting and vetting.
# - Integration tests are opt-in by setting RUN_INTEGRATION=true in the CI.
# - Secrets (DB_PASSWORD, JWT secrets) should be configured in CodeRabbit and
#   referenced securely — never store secrets in the repo.

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  BACKEND_DIR: backend
  GO_VERSION: 1.21
  RUN_INTEGRATION: "false"  # Set to "true" in CI to enable integration steps.

jobs:
  lint:
    name: Lint & Static Checks
    image: golang:${GO_VERSION}
    steps:
      - name: Checkout code
        run: |
          # Runner should perform checkout here. Replace with appropriate step.
          git clone ${{ repo.clone_url }} . || true

      - name: Lint & vet
        run: |
          cd ${BACKEND_DIR}
          # Fetch modules, but do not change source files
          go env -w GO111MODULE=on
          go mod download

          # Formatting check (fail on differences)
          if [ -n "$(gofmt -l .)" ]; then
            echo "gofmt found files not formatted:"; gofmt -l .; exit 1
          fi

          # Vet checks — recommended but don't auto-fix
          go vet ./... || true

  unit_tests:
    name: Unit Tests
    image: golang:${GO_VERSION}
    needs: [lint]
    steps:
      - name: Checkout code
        run: git clone ${{ repo.clone_url }} . || true

      - name: Run unit tests
        run: |
          cd ${BACKEND_DIR}
          go env -w GO111MODULE=on
          go mod download
          # Run only non-integration unit tests (use tags or package selection if needed)
          go test ./... -v

  build:
    name: Build (no artifacts committed)
    image: golang:${GO_VERSION}
    needs: [unit_tests]
    steps:
      - name: Checkout code
        run: git clone ${{ repo.clone_url }} . || true

      - name: Build backend binary (temporary)
        run: |
          cd ${BACKEND_DIR}
          go env -w GO111MODULE=on
          go mod download
          # Build the binary into a temporary directory to avoid modifications in repo workspace
          mkdir -p /tmp/build
          go build -o /tmp/build/server ./cmd/server

  integration_tests:
    name: Integration Tests (Optional)
    image: docker:stable
    services:
      - docker:dind
    needs: [build]
    if: "${{ env.RUN_INTEGRATION }} == 'true'"
    steps:
      - name: Checkout code
        run: git clone ${{ repo.clone_url }} . || true

      - name: Start infrastructure (docker-compose)
        run: |
          cd ${BACKEND_DIR}
          # Run docker-compose in the runner. Ensure the runner supports Docker
          docker-compose up -d
          # Wait for services readiness (customize if necessary)
          for i in $(seq 1 30); do
            docker exec -it base-app-postgres pg_isready -U baseapp &>/dev/null && break
            echo "Waiting for postgres... ($i)"; sleep 2
          done

      - name: Run migrations & API tests
        run: |
          cd ${BACKEND_DIR}
          chmod +x scripts/migrate.sh || true
          scripts/migrate.sh up || true
          chmod +x scripts/test-api.sh || true
          scripts/test-api.sh || true

      - name: Tear down
        run: |
          cd ${BACKEND_DIR}
          docker-compose down -v || true

# End of pipeline
# Additional recommendations:
# - Add caching for Go module downloads to speed up CI runs.
# - If your CodeRabbit runner checks out the repo already, remove the git clone lines and use the runner-provided checkout.
# - Configure required secrets in CodeRabbit (DB_PASSWORD, JWT_SECRET, etc.).
